"""add: owner_id to project table

Revision ID: 000cd1085c76
Revises: 273ff3608041
Create Date: 2026-06-07 21:33:43.364560

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "000cd1085c76"
down_revision: Union[str, Sequence[str], None] = "273ff3608041"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("owner_id", sa.UUID(), nullable=False))
    op.create_unique_constraint(None, "projects", ["owner_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", type_="unique")
    op.drop_column("projects", "owner_id")
    # ### end Alembic commands ###
