"""add on dleete cascade for project_user project_id fk

Revision ID: 06d0a0924b08
Revises: 0f8c29054502
Create Date: 2026-06-21 00:05:14.855330

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "06d0a0924b08"
down_revision: Union[str, Sequence[str], None] = "0f8c29054502"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
