"""add: status to apikey table

Revision ID: 0f8c29054502
Revises: a127b65a5a2b
Create Date: 2026-06-20 19:35:10.561802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f8c29054502"
down_revision: Union[str, Sequence[str], None] = "a127b65a5a2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys",
        sa.Column(
            "status", sa.Enum("ACTIVE", "INACTIVE", name="apikeystatus"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_keys", "status")
    # ### end Alembic commands ###
