"""bug: project_table allowed for only one user

Revision ID: 2223e2aed453
Revises: 69d6e0fb8298
Create Date: 2026-06-14 19:44:16.328102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2223e2aed453'
down_revision: Union[str, Sequence[str], None] = '69d6e0fb8298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('projects_owner_id_key'), 'projects', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('projects_owner_id_key'), 'projects', ['owner_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
