"""add: index on FKs

Revision ID: 3598ae4dc64e
Revises: 2223e2aed453
Create Date: 2026-06-14 19:48:31.050485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3598ae4dc64e'
down_revision: Union[str, Sequence[str], None] = '2223e2aed453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_dutyys_project_id'), 'dutyys', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dutyys_project_id'), table_name='dutyys')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    # ### end Alembic commands ###
