"""add csrf token next to websession

Revision ID: 3feac35f8f12
Revises: 228c099196c5
Create Date: 2026-09-18 21:48:08.370694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3feac35f8f12'
down_revision: Union[str, Sequence[str], None] = '228c099196c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_sessions', sa.Column('csrf_token', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'web_sessions', ['csrf_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web_sessions', type_='unique')
    op.drop_column('web_sessions', 'csrf_token')
    # ### end Alembic commands ###
