"""add: password_set_tokens_table for via welcome emails

Revision ID: 445231cabf23
Revises: c1d9cb435b88
Create Date: 2026-07-06 23:23:28.860370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "445231cabf23"
down_revision: Union[str, Sequence[str], None] = "c1d9cb435b88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_token",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_token_token_hash"),
        "password_token",
        ["token_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_token_user_id"), "password_token", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_password_token_user_id"), table_name="password_token")
    op.drop_index(op.f("ix_password_token_token_hash"), table_name="password_token")
    op.drop_table("password_token")
    # ### end Alembic commands ###
