"""add: on delete cascade for user fks

Revision ID: 5875e64f2c61
Revises: 3598ae4dc64e
Create Date: 2026-06-15 21:33:37.293286

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5875e64f2c61"
down_revision: Union[str, Sequence[str], None] = "3598ae4dc64e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("api_keys_user_id_fkey"), "api_keys", type_="foreignkey")
    op.create_foreign_key(
        None, "api_keys", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("project_user_user_id_fkey"), "project_user", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "project_user", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project_user", type_="foreignkey")
    op.create_foreign_key(
        op.f("project_user_user_id_fkey"), "project_user", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "api_keys", type_="foreignkey")
    op.create_foreign_key(
        op.f("api_keys_user_id_fkey"), "api_keys", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
