"""remove nullability on device_auth_code.c.user_code

Revision ID: 928bacee38d6
Revises: 9b14813053f2
Create Date: 2026-08-21 22:55:02.456289

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "928bacee38d6"
down_revision: Union[str, Sequence[str], None] = "9b14813053f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "device_auth_code", "user_code", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "device_auth_code", "user_code", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
