"""rename: device_auth_code.c.auth_code -> device_auth_code.c.hashed_device_code

Revision ID: 9b14813053f2
Revises: c3a0f09078ee
Create Date: 2026-08-20 17:46:41.595188

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9b14813053f2'
down_revision: Union[str, Sequence[str], None] = 'c3a0f09078ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_auth_code',
    sa.Column('hashed_device_code', sa.String(), nullable=False),
    sa.Column('user_code', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'CONSUMED', name='devicecodestatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hashed_device_code')
    )
    op.create_index(op.f('ix_device_auth_code_user_code'), 'device_auth_code', ['user_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_auth_code_user_code'), table_name='device_auth_code')
    op.drop_table('device_auth_code')
    # ### end Alembic commands ###
