"""add: modified_date column

Revision ID: 9bab3bd4e39c
Revises: a42e594060ed
Create Date: 2026-06-05 17:02:38.926564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bab3bd4e39c"
down_revision: Union[str, Sequence[str], None] = "a42e594060ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "modified_date")
    # ### end Alembic commands ###
