"""empty message

Revision ID: a127b65a5a2b
Revises: 5875e64f2c61
Create Date: 2026-06-20 14:56:33.941696

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a127b65a5a2b"
down_revision: Union[str, Sequence[str], None] = "5875e64f2c61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("project_user_project_id_fkey"), "project_user", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "project_user", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project_user", type_="foreignkey")
    op.create_foreign_key(
        op.f("project_user_project_id_fkey"),
        "project_user",
        "projects",
        ["project_id"],
        ["id"],
    )
    # ### end Alembic commands ###
