"""remove: salt from user_table - found that pwdlib does it with Argon2

Revision ID: a98ec28b533e
Revises: ade1750b5dd4
Create Date: 2026-06-27 00:53:55.343917

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a98ec28b533e"
down_revision: Union[str, Sequence[str], None] = "ade1750b5dd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password_hash", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
