"""add: salt to user_table

Revision ID: ade1750b5dd4
Revises: 06d0a0924b08
Create Date: 2026-06-27 00:50:20.227877

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ade1750b5dd4"
down_revision: Union[str, Sequence[str], None] = "06d0a0924b08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("salt", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "salt")
    # ### end Alembic commands ###
