"""use the actual enum not string literal

Revision ID: c3a0f09078ee
Revises: d2f7c57bf9ef
Create Date: 2026-08-11 20:26:28.899575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a0f09078ee'
down_revision: Union[str, Sequence[str], None] = 'd2f7c57bf9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
