"""fix: cascade on delete and hydration issue for projects

Revision ID: c7ef1de0de06
Revises: e09c974ce465
Create Date: 2026-09-03 10:32:16.289849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ef1de0de06'
down_revision: Union[str, Sequence[str], None] = 'e09c974ce465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dutyys_project_id_fkey'), 'dutyys', type_='foreignkey')
    op.create_foreign_key(None, 'dutyys', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dutyys', type_='foreignkey')
    op.create_foreign_key(op.f('dutyys_project_id_fkey'), 'dutyys', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
