"""add partial_composite_index to api_key_table

Revision ID: d2f7c57bf9ef
Revises: 445231cabf23
Create Date: 2026-08-11 20:18:48.329599

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd2f7c57bf9ef'
down_revision: Union[str, Sequence[str], None] = '445231cabf23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_api_keys_active_name', 'api_keys', ['user_id', 'name'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_api_keys_active_name', table_name='api_keys', postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###
