"""new columns for publishing status on projects table

Revision ID: e09c974ce465
Revises: 26ec71c9b291
Create Date: 2026-08-30 20:55:02.448012

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e09c974ce465"
down_revision: Union[str, Sequence[str], None] = "26ec71c9b291"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    publishingstatus = sa.Enum("DRAFT", "PUBLISHED", name="publishingstatus")
    publishingstatus.create(op.get_bind())
    op.add_column(
        "projects", sa.Column("publishing_status", publishingstatus, nullable=False)
    )
    op.add_column(
        "projects",
        sa.Column("published_date", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "published_date")
    op.drop_column("projects", "publishing_status")
    # ### end Alembic commands ###
