name: lint
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint and Format checker
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v1
        with:
          version: "latest"
      - run: uv sync --locked
      - run: uv run ruff check --output-format=github .
      - run: uv run ruff format --check .
